// <auto-generated/>
#nullable enable
/// <inheritdoc/>
namespace Pretender.SourceGeneration
{
    using System.Reflection;
    using Pretender;

    /// <inheritdoc/>
    internal class PretendISimpleInterface19445CC : global::ISimpleInterface
    {
        public static readonly MethodInfo MethodInfo_Foo_2F42C5 = typeof(global::ISimpleInterface).GetMethod(nameof(Foo))!;
        public static readonly MethodInfo MethodInfo_VoidMethod_24F1739 = typeof(global::ISimpleInterface).GetMethod(nameof(VoidMethod))!;
        public static readonly MethodInfo MethodInfo_AsyncMethod_17D862F = typeof(global::ISimpleInterface).GetMethod(nameof(AsyncMethod))!;
        public static readonly MethodInfo MethodInfo_AsyncReturningMethod_165B12 = typeof(global::ISimpleInterface).GetMethod(nameof(AsyncReturningMethod))!;
        public static readonly MethodInfo MethodInfo_TryParse_35A6CCF = typeof(global::ISimpleInterface).GetMethod(nameof(TryParse))!;
        public static readonly MethodInfo MethodInfo_get_Bar_2968A4B = typeof(global::ISimpleInterface).GetProperty(nameof(Bar)).GetMethod!;
        public static readonly MethodInfo MethodInfo_set_Bar_28FB0B7 = typeof(global::ISimpleInterface).GetProperty(nameof(Bar)).SetMethod!;
        private readonly Pretend<global::ISimpleInterface> _pretend;
        /// <inheritdoc/>
        public PretendISimpleInterface19445CC(Pretend<global::ISimpleInterface> pretend)
        {
            _pretend = pretend;
        }

        public string? Foo(string? bar, int baz)
        {
            object? [] __arguments = [bar, baz];
            var __callInfo = new CallInfo(MethodInfo_Foo_2F42C5, __arguments);
            _pretend.Handle(__callInfo);
            return (string? )__callInfo.ReturnValue;
        }

        public void VoidMethod(bool baz)
        {
            object? [] __arguments = [baz];
            var __callInfo = new CallInfo(MethodInfo_VoidMethod_24F1739, __arguments);
            _pretend.Handle(__callInfo);
        }

        public global::System.Threading.Tasks.Task AsyncMethod()
        {
            object? [] __arguments = [];
            var __callInfo = new CallInfo(MethodInfo_AsyncMethod_17D862F, __arguments);
            _pretend.Handle(__callInfo);
            return (global::System.Threading.Tasks.Task)__callInfo.ReturnValue;
        }

        public global::System.Threading.Tasks.Task<string> AsyncReturningMethod(string bar)
        {
            object? [] __arguments = [bar];
            var __callInfo = new CallInfo(MethodInfo_AsyncReturningMethod_165B12, __arguments);
            _pretend.Handle(__callInfo);
            return (global::System.Threading.Tasks.Task<string>)__callInfo.ReturnValue;
        }

        public bool TryParse(string thing, out bool myValue)
        {
            object? [] __arguments = [thing, myValue];
            var __callInfo = new CallInfo(MethodInfo_TryParse_35A6CCF, __arguments);
            _pretend.Handle(__callInfo);
            myValue = __arguments[1];
            return (bool)__callInfo.ReturnValue;
        }

        public string Bar
        {
            get
            {
                object? [] __arguments = [];
                var __callInfo = new CallInfo(MethodInfo_get_Bar_2968A4B, __arguments);
                _pretend.Handle(__callInfo);
                return (string)__callInfo.ReturnValue;
            }

            set
            {
                object? [] __arguments = [value];
                var __callInfo = new CallInfo(MethodInfo_set_Bar_28FB0B7, __arguments);
                _pretend.Handle(__callInfo);
            }
        }
    }
}